spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academy
    username: kashark
    password: 081125kashark

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl